obj-m := mc24lc64t.o baseboard_cpld.o switchboard_fpga.o int_switchboard_fpga.o  dimm-bus.o i2c-imc.o
KBUILD_EXTRA_SYMBOLS := /sonic/platform/broadcom/sonic-platform-modules-cel/shamu/Ali_ko/Module.symvers
KBUILD_EXTRA_SYMBOLS += /sonic/src/sonic-linux-kernel/linux-4.9.189/debian/build/build_amd64_none_amd64/Module.symvers
