#!/bin/bash
#
# Copyright 2019-present Celestica. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

prog="$0"

usage() {
    echo "Usage: bmc-exec <command>"
    echo
}

run_cmd() {
    curl -m 5 -d '{"data":"'$*'"}' http://240.1.1.1:8080/api/sys/raw
    ret=$?
    if [ $ret -ne 0 ]; then
       echo "Failed to run command on BMC"
    fi
    return 0
}

if [ $# -lt 1 ]; then
    usage
    exit -1
else
    run_cmd
fi

exit $?
