depmod -a

# Copy rsyslog configuration files and templates
cp /usr/local/etc/rsyslog /etc/logrotate.d/rsyslog

# Enable bmc vlan_ip service
systemctl enable bmc_vlan.service

systemctl enable platform-modules-fishbone32.service
systemctl start platform-modules-fishbone32.service

# Enable platform-sync_bmc-timer
# systemctl enable sync_bmc.timer
# systemctl start sync_bmc.timer

# Enable heartbeat timer
systemctl enable bmc_wdt.service
systemctl start bmc_wdt.service
