obj-m := mc24lc64t.o baseboard_cpld.o switchboard_fpga.o i2c-imc.o dimm-bus.o int_switchboard_fpga.o
KBUILD_EXTRA_SYMBOLS := /sonic/platform/broadcom/sonic-platform-modules-alibaba/common/modules/Module.symvers
KBUILD_EXTRA_SYMBOLS += /sonic/src/sonic-linux-kernel/linux-4.9.189/debian/build/build_amd64_none_amd64/Module.symvers
