#!/bin/sh
set -e
# Automatically added by dh_installinit/12.1.1~bpo9+1
if [ "$1" = "purge" ] ; then
	update-rc.d platform-modules-dx010 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installmodules/12.1.1~bpo9+1
if [ -e /boot/System.map-4.9.0-11-2-amd64 ]; then
	depmod -a -F /boot/System.map-4.9.0-11-2-amd64 4.9.0-11-2-amd64 || true
fi
# End automatically added section
